### ISSUE TITLE
Parsing issues

### ISSUE THREAD

**Issue by arvislacis** [skripteria/wn-snowflake-plugin#18]
As I already briefly mentioned in https://github.com/skripteria/wn-snowflake-plugin/discussions/16 then current Snowflake parser has some interesting behavior in some edge cases, maybe nothing too critical and the most users would not face them but, anyways, at some point in time the current parsing method should be improved.

Current issues:

- [x]  Double quotes are not escaped correctly at line https://github.com/skripteria/wn-snowflake-plugin/blob/525601f2b41adcf394272e67f78d8a2cf640975e/classes/SnowflakeParser.php#L27 it should be `str_replace(['\'', '"'], '', $param_string);` - because now it tries to replace escaping of double quotes; 
- [x] The overall `str_replace` approach is not very good because it also replaces every other single and double quote which may be in the `sf()` filter, some examples:

````twig
    {{ test_key|sf('text', "tests", 'Test "quote" description...') }}
    {{ test_key2|sf('text', "'tests'", "'Test 'quote' description'...") }}
````

- [ ] As I mentioned in https://github.com/skripteria/wn-snowflake-plugin/discussions/16 then there is problem with brackets `()` - probably problem with existing initial regex, some example:

````twig
    {{ test_color|sf('color', 'tests', 'Test description (new)') }}
    {{ test_image|sf('image', 'image', 'Test description (new)...') }}
    {{ test_file|sf('file', 'file', 'File description (new)...') }}
````

^ Everything after the **(new** is removed;

- [x] https://github.com/skripteria/wn-snowflake-plugin/blob/525601f2b41adcf394272e67f78d8a2cf640975e/classes/SnowflakeParser.php#L29 - because of the way how commas are processed, there may be issues if commas (`,`) is used in description or default value parameter.

**Comment by arvislacis** [comment]
Overall these issues are nothing too problematic, well, maybe the last one about commas may cause bigger problems when parser would detect more or different parameters than developer actually expected...

If I will have some spare time, I may also look at these issues and how to solve them. But currently I am just mentioning them here so you are informed.

**Comment by skripteria** [comment]
I have now figured out a improved method that even works with special charactes (brackets, commas etc.) however it still wouldnt allow quotes (' or ") within an argument.
I think even this is a significant improvement in comparison to the current behaviour.

**Comment by skripteria** [comment]
update: finally ... I believe I have found the regex pattern that works!
I will continue testing now, but so far it looks promising.

**Comment by arvislacis** [comment]
@skripteria That's nice :) Although if your regex is about fixing matching closing brackets `)` then you could probably merge https://github.com/skripteria/wn-snowflake-plugin/pull/23 without problems.

**Comment by skripteria** [comment]
...thats right, its likely that both pieces work together nicely. Since I am still doing a lot detail work and tests I will then probably use whatever code gives the best results on our edge cases.

**Comment by skripteria** [comment]
as you said: works together nicely. My method (parsing the $param_string with preg_match_all) and your way using str_getcsv work fine and deliver identical results. Both ways dont support a comma ',' inside, but thats acceptable.

I only found one odd edge case when I deliberately messed up the tag - here the regex method showed the slightly better result. Doesnt make a real difference, but it makes the decision easier to choose the regex way.

Overall I am happy with the results, lets hope I havent overseen anything!
