### ISSUE TITLE
Content preview

### ISSUE THREAD

**Issue by skripteria** [skripteria/wn-snowflake-plugin#7]
Last small feature I want to add before I believe V1.0 is ready for final tests and release:

In the list view of the content elements I like to add a short preview of the current content (say first 50 characters). This will not work for images and files but still may help site editors help to keep the orientation.

Any more suggestions?

**Comment by arvislacis** [comment]
I guess that you already implemented this in https://github.com/skripteria/wn-snowflake-plugin/commit/45f61fc4a4779066686e07328c2dfbc1d0c71dbb so this issue may be closed.

As for other things, improvements - currently I don't have more major ideas or suggestions. There are some things which can be improved always but I think they can be addressed also later, for example:

1.  I don't know where https://github.com/skripteria/wn-snowflake-plugin/blob/3c1808917a676713fed44ea1d21c17f3be84f583/components/BlueprintPage.php and https://github.com/skripteria/wn-snowflake-plugin/blob/e83bc70c2fe09db032154d1d65e44030750b9167/models/RealnameFile.php files are used? Are they redundant from some historical functionality or it's unfinished features?
2. What is the idea behind Position (`order`) column? Does it affect priority of which Snowflake Key value is used when key collision happens or? If so then maybe Sortable Trait could be implemented for the record list so users can also change priority or sort them as they wish..., although these values probably will change after every `syncDb`...
3. I personally find this code part a bit confusing in parser function:

```php
foreach ($params as $i => $param) {
    switch ($i) {
        case 0:
            $tags[$sf_key]['type'] = $param;

            break;
        case 1:
            if ($tags[$sf_key]['type'] !== 'image' && $tags[$sf_key]['type'] !== 'file') {
                $tags[$sf_key]['default'] = $param;
            }

            break;
        case 2:
            $tags[$sf_key]['desc'] = $param;

            break;
    }
}
```

Usually `switch` statement is not used to process loop index values so it takes a moment to understand the logic behind this. Maybe in the future this can be rewritten using just simple `if` statements, for example:

```php
if (isset($params[0])) {
    $tags[$sf_key]['type'] = $params[0];
}

if (isset($params[1])) {
    if ($tags[$sf_key]['type'] !== 'image' && $tags[$sf_key]['type'] !== 'file') {
        $tags[$sf_key]['default'] = $params[1];
    }
}

if (isset($params[2])) {
    $tags[$sf_key]['desc'] = $params[2];
}
```

^ This would avoid second `foreach` and `switch` statements at all. Anyways, this need to be tested - it's just a fast prototype code from me.

**Comment by arvislacis** [comment]
Speaking about content preview - as you have implement the preview column as partial then in theory you could also output image thumbnail, output colorpicker value as colored text or rectangle, similar like `colorpicker` column type:

![2021-12-11_18-56](https://user-images.githubusercontent.com/626982/145684976-a33ab312-0cf0-4817-ab59-e6c2dc59f1b3.png)

Maybe even file paths and links could be outputted as hyperlinks which could be clicked and the content editor could preview corresponding content in the new tab (hyperlinks with `_target`).

**Comment by skripteria** [comment]
1. RealnameFile.php: This reflects an idea to support the original file name of the upload for SEO reasons. However the longer I thought about this feature the cons weighed out the pros and I decided against it. No reason to keep it any longer.
BlueprintPage.php: This is already a preparation for later developing ideas to support Themes that come with the market place. I want to keep it for now.
2. The order column ensures that the Snowflake elements show always up in the order they are used in the markup. First element in the markup will be first element in the list etc. . In the sync there is a mechanism to refresh this for the case SF elements will be moved around.

About the content preview: 👍  good idea, I and had similiar thoughts before. I suggest to postpone it to a later release because its useful but not really vital to need it from the very beginning.

I will have a closer look at the code suggestions, I know some parts of it will be a tought one for me since I always was the lonely rebel who was questioning the habit that  everything  has to be a class ourdays. But to be honest my fuctional way using the init.php doesnt come with a a real benefit. 
So probably I will stop my rebellion for a while :)

**Comment by arvislacis** [comment]
Personally I am also against high level OOP and class usage - when you abstract class of already abstract class/type etc. but overall I think class approach is good and can benefit a lot, even when just used for separating different code parts in different classes.

The main reason to move `init.php` functions under the new class was not to introduce another new class but mostly because, I think, `init.php` file gets executed (loaded in memory) every time your plugin and/or component is executed so class approach would solve this problem and give a very, very, very small performance improvement.

**Comment by skripteria** [comment]
About the switch statement: I can see your point here but the current way has produced reliable results so lets leave it as it is right now, I dont want to risk a new bug here. 
So, I think we have a release candidate for Snowflake 1.0 now. I will now test the core features again, then publish it to packagist. Any new work will then be for the following releases.

**Comment by arvislacis** [comment]
Ok. Good luck. :)

**Comment by skripteria** [comment]
All up and running. Thanks a lot for your help! 🥇

**Comment by arvislacis** [comment]
@skripteria No problem. As I said before - looks like a nice idea and plugin. So wait for my pull requests and suggestions also in the future.

As plugin is now available on Packagist then it's probably also a good idea to update README later to include Packagist (composer) installation method too - most users probably would find it more easier for installation and updating.
