### ISSUE TITLE
About FA icon

### ISSUE THREAD

**Issue by arvislacis** [skripteria/wn-snowflake-plugin#9]
You can actually avoid using `icons.css` file if you replace `icon-snowflake` with `icon-snowflake-o` in code so Font Awesome icon from Winter CMS core will be used - https://fontawesome.com/v4.7/icon/snowflake-o

- https://github.com/skripteria/wn-snowflake-plugin/blob/01d770ec731c727b25e000543431af5245845cc8/Plugin.php#L81
- https://github.com/skripteria/wn-snowflake-plugin/blob/01d770ec731c727b25e000543431af5245845cc8/Plugin.php#L107
- https://github.com/skripteria/wn-snowflake-plugin/blob/59518fcd2f48c323934a4246c4b4485ba83d2e67/components/SfPage.php#L19

Currently I left this on hold because probably https://github.com/skripteria/wn-snowflake-plugin/pull/8 should be merged or rejected first.

**Comment by skripteria** [comment]
oohps, I must have overlooked the icon-snowflake-o when I checked the core. 
Of course this is much better, glad you found it.
